### ISSUE TITLE
Perhaps not the fastest

### ISSUE THREAD

**Issue by anywhichway** [ehmicky/big-cartesian#11]
Although they are generally within each other's margin of error, [CXProduct](https://github.com/anywhichway/cxproduct), seems to be slightly faster for small combinations. For moderate size combinations it is much faster. And, CXProduct is much faster than big-cartesian at scale. Since CXProduct has a number of extras, you could probably write a version of fast-cartesian or big-cartesian that uses the same virtual product approach and outperforms CXProduct while being smaller. You could then drop to a single repo. Take a look at the source for CXProduct and at this: http://phrogz.net/lazy-cartesian-product.

**Comment by ehmicky** [comment]
hi @anywhichway,

`cxproduct` should be compared to `big-cartesian`, not to `fast-cartesian`. Unlike those two first libraries, `fast-cartesian` creates and returns a single array that stores all combinations. On the other hand, `cxproduct` and `big-cartesian` only iterate through each combination. 
  - The former is better for some use cases, e.g. when the whole array must be pre-computed for later. Some users might find getting a single return value simpler than iterating over each combination as well. 
  - The latter is better for memory consumption. It also avoids the maximum size of arrays in JavaScript.

Therefore, in order to fairly compare the performance of `cxproduct` and `fast-cartesian`, the benchmarking logic must make sure an array is created by `cxproduct`.

```js
const arrayOne = []
new CXProduct(matrix).forEach((value) => {
  arrayOne.push(value)
})

const arrayTwo = fastCartesian(matrix)
```

When doing so, `fast-cartesian` [appears to be faster](https://github.com/ehmicky/fast-cartesian/blob/main/README.md#benchmarks).

That being said, `cxproduct` is [faster than `big-cartesian`](https://github.com/ehmicky/fast-cartesian/blob/main/README.md#benchmarks). However, unlike `fast-cartesian`, `big-cartesian`'s purpose is not speed but convenience. In particular, it returns an iterator, which is convenient for users as it allows using a `for (... of ...)` loop. On the other hand, iterators always tend to be a little slower than direct loops.

**Comment by anywhichway** [comment]
Then you should probably add a caveat to your documentation "[Fastest](https://github.com/ehmicky/fast-cartesian#benchmarks) available library in JavaScript." should probably be "[Fastest](https://github.com/ehmicky/fast-cartesian#benchmarks) available library in JavaScript that returns an actual array."

With respect to generators, the latest version CXProduct has a method asGenerator, so if people want to use for(...) instead of forEach, they can. It also has a method asArrayLike which supports blazing fast use of for(;;).

I'll leave things as this unless you ask for further feedback, not trying to be difficult.
